### ISSUE TITLE
Checking main command does not output unless verbose specified

### ISSUE THREAD

**Issue by isaac-philip** [ewen-lbh/check-availability#3]
Great utility we have here!

As a python executable, I need to be able to quickly check on the command line if a relevant python project name is available or not.

It seems by default the output does not appear and had to specify explicitly to get the output.

Details below,

```shell
╰─$ check-availability pypi temp
# No output here
╰─$ check-availability pypi temp --verbose=3                                                       
GET https://pypi.org/project/temp
Got status code 200
The name temp is not available on pypi
```

As a user my expectation is to receive the output immediately rather than having explicit parameters to retrieve it.

If this makes sense I can proceed to have the fix added.

**Comment by isaac-philip** [comment]
whats the  opinion  @ewen-lbh for it?

**Comment by gwennlbh** [comment]
Well, following the UNIX way, I made the response a return code. Of course, responding with actual output is beneficial and does not get in the way of programmatic use, so I'll definitely add that. It's pretty trivial so I can code it myself but you can also open a PR, I'll gladly merge it.

**Comment by isaac-philip** [comment]
Hello @ewen-lbh  , kindly review & merge if good, thanks
